# Generated by Django 4.2.30 on 2026-05-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile_personal_notes_meallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_unit',
            field=models.CharField(choices=[('lb', 'Pounds (lb)'), ('kg', 'Kilograms (kg)')], default='lb', max_length=2),
        ),
    ]
