# Generated by Django 4.2.30 on 2026-05-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_preferred_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
