# Generated by Django 4.2.30 on 2026-05-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_workoutplan_activated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.CharField(max_length=100),
        ),
    ]
