# Generated by Django 4.2.30 on 2026-05-05 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_health_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthconnection',
            name='terra_user_id',
        ),
    ]
