# Generated by Django 4.2.30 on 2026-05-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_terra_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdailysummary',
            name='resting_calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
