# Generated by Django 4.2.30 on 2026-05-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_healthdailysummary_resting_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthconnection',
            name='sync_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
