# Generated by Django 4.2.30 on 2026-06-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_chatsession_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutday',
            name='last_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
