# Generated by Django 4.2.30 on 2026-06-24 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_workoutday_last_completed_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutday',
            options={'ordering': ['week_number', 'order']},
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='current_week',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='goal_check_in_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='program_target',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='specific_goal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='workoutday',
            unique_together={('plan', 'week_number', 'day_number')},
        ),
        migrations.CreateModel(
            name='ProgramCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(max_length=100)),
                ('start_value', models.FloatField(blank=True, null=True)),
                ('end_value', models.FloatField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='api.workoutplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
