# Generated by Django 4.2.30 on 2026-06-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_week_progression'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthconnection',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
